// Zaevyul Pashmina — Realistic Mock Data

export const MOCK_ADMINS = [
  {
    id: 'adm-001',
    name: 'Raza Mir',
    email: 'super@zaevyul.com',
    password: 'admin123',
    role: 'super_admin',
    avatar: null,
    initials: 'RM',
    lastLogin: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'adm-002',
    name: 'Sana Khan',
    email: 'admin@zaevyul.com',
    password: 'admin123',
    role: 'admin',
    avatar: null,
    initials: 'SK',
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'adm-003',
    name: 'Amir Shah',
    email: 'editor@zaevyul.com',
    password: 'admin123',
    role: 'editor',
    avatar: null,
    initials: 'AS',
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const MOCK_CATEGORIES = [
  { id: 'cat-001', name: 'Shawls', slug: 'shawls', description: 'Handwoven Kashmiri shawls in pure Pashmina', productCount: 8, sortOrder: 1, status: 'active', banner: null, mainImage: null, seo: { title: 'Pure Pashmina Shawls - Handwoven Kashmiri Collection', description: 'Explore our handwoven Kashmiri shawls in pure Pashmina, crafted by master artisans.', url: 'shawls' } },
  { id: 'cat-002', name: 'Stoles', slug: 'stoles', description: 'Lightweight Pashmina stoles for everyday elegance', productCount: 5, sortOrder: 2, status: 'active', banner: null, mainImage: null, seo: { title: 'Elegant Pashmina Stoles - Handcrafted Collection', description: 'Shop our lightweight Pashmina stoles for everyday elegance. 100% genuine Kashmiri craft.', url: 'stoles' } },
  { id: 'cat-003', name: 'Blankets', slug: 'blankets', description: 'Luxurious Pashmina blankets and throws', productCount: 3, sortOrder: 3, status: 'active', banner: null, mainImage: null, seo: { title: 'Luxurious Pashmina Blankets & Throws', description: 'Wrap yourself in the luxurious warmth of pure Pashmina blankets and throws.', url: 'blankets' } },
  { id: 'cat-004', name: 'Scarves', slug: 'scarves', description: 'Fine Pashmina scarves in seasonal tones', productCount: 3, sortOrder: 4, status: 'active', banner: null, mainImage: null, seo: { title: 'Fine Pashmina Scarves - Seasonal Tones', description: 'Beautiful fine Pashmina scarves in gorgeous seasonal tones to elevate your wardrobe.', url: 'scarves' } },
  { id: 'cat-005', name: 'Accessories', slug: 'accessories', description: 'Pashmina caps, gloves, and wraps', productCount: 1, sortOrder: 5, status: 'active', banner: null, mainImage: null, seo: { title: 'Pashmina Accessories - Handcrafted Caps & Gloves', description: 'Shop genuine Pashmina accessories including warm caps, fingerless gloves, and wraps.', url: 'accessories' } },
];

const now = Date.now();
const day = 1000 * 60 * 60 * 24;export const MOCK_PRODUCTS = [
  { id: 'prd-001', name: 'Himalayan Snow Shawl', slug: 'himalayan-snow-shawl', sku: 'ZAE-SH-001', category: 'cat-001', basePrice: 12500, discountPrice: 10800, costPrice: 5200, quantity: 24, lowStockThreshold: 5, status: 'published', tags: ['bestseller', 'winter'], material: '100% Pashmina', color: 'Ivory', size: 'Large (200×70cm)', description: 'Hand-spun and handwoven in the valleys of Kashmir, this ivory shawl carries the quiet warmth of Himalayan winters.', images: [{ id: 'img-001a', name: 'snow-1', url: '/storefront/prod-1.png' }, { id: 'img-001b', name: 'snow-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 30*day).toISOString() },
  { id: 'prd-002', name: 'Saffron Garden Stole', slug: 'saffron-garden-stole', sku: 'ZAE-ST-001', category: 'cat-002', basePrice: 6800, discountPrice: null, costPrice: 2800, quantity: 18, lowStockThreshold: 4, status: 'published', tags: ['new-arrival'], material: '100% Pashmina', color: 'Saffron', size: 'Standard (190×60cm)', description: 'Inspired by Kashmir\'s famed saffron fields, woven in rich earthy tones.', images: [{ id: 'img-002a', name: 'saffron-1', url: '/storefront/cat-stoles.png' }, { id: 'img-002b', name: 'saffron-2', url: '/storefront/prod-3.png' }], createdAt: new Date(now - 25*day).toISOString() },
  { id: 'prd-003', name: 'Walnut Wood Shawl', slug: 'walnut-wood-shawl', sku: 'ZAE-SH-002', category: 'cat-001', basePrice: 14200, discountPrice: 12500, costPrice: 6100, quantity: 12, lowStockThreshold: 5, status: 'published', tags: ['bestseller'], material: '100% Pashmina', color: 'Walnut Brown', size: 'Large (200×70cm)', description: 'Deep warm tones of aged walnut wood, woven into a piece of lasting heritage.', images: [{ id: 'img-003a', name: 'walnut-1', url: '/storefront/prod-3.png' }, { id: 'img-003b', name: 'walnut-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 22*day).toISOString() },
  { id: 'prd-004', name: 'Glacier Blue Stole', slug: 'glacier-blue-stole', sku: 'ZAE-ST-002', category: 'cat-002', basePrice: 7200, discountPrice: null, costPrice: 3000, quantity: 3, lowStockThreshold: 4, status: 'published', tags: ['limited'], material: '100% Pashmina', color: 'Glacier Blue', size: 'Standard (190×60cm)', description: 'The serene clarity of mountain glaciers, rendered in delicate Pashmina threads.', images: [{ id: 'img-004a', name: 'glacier-1', url: '/storefront/cat-scarves.png' }, { id: 'img-004b', name: 'glacier-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 20*day).toISOString() },
  { id: 'prd-005', name: 'Cedar Forest Blanket', slug: 'cedar-forest-blanket', sku: 'ZAE-BL-001', category: 'cat-003', basePrice: 22000, discountPrice: 19500, costPrice: 9800, quantity: 8, lowStockThreshold: 3, status: 'published', tags: ['bestseller', 'gift'], material: '100% Pashmina', color: 'Deep Green', size: 'King (240×120cm)', description: 'Heavy Pashmina throw in the dense green of Kashmiri cedar forests.', images: [{ id: 'img-005a', name: 'cedar-1', url: '/storefront/prod-stack.png' }, { id: 'img-005b', name: 'cedar-2', url: '/storefront/prod-3.png' }], createdAt: new Date(now - 18*day).toISOString() },
  { id: 'prd-006', name: 'Morning Mist Scarf', slug: 'morning-mist-scarf', sku: 'ZAE-SC-001', category: 'cat-004', basePrice: 4500, discountPrice: null, costPrice: 1800, quantity: 31, lowStockThreshold: 6, status: 'published', tags: ['everyday'], material: '70% Pashmina, 30% Silk', color: 'Grey Mist', size: 'Standard (170×50cm)', description: 'Feather-light scarf in the pale grey of Dal Lake mornings.', images: [{ id: 'img-006a', name: 'mist-1', url: '/storefront/cat-scarves.png' }, { id: 'img-006b', name: 'mist-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 16*day).toISOString() },
  { id: 'prd-007', name: 'Autumn Meadow Shawl', slug: 'autumn-meadow-shawl', sku: 'ZAE-SH-003', category: 'cat-001', basePrice: 11800, discountPrice: null, costPrice: 5000, quantity: 15, lowStockThreshold: 5, status: 'published', tags: ['seasonal'], material: '100% Pashmina', color: 'Warm Amber', size: 'Large (200×70cm)', description: 'The golden hours of a Kashmiri autumn captured in warm amber weave.', images: [{ id: 'img-007a', name: 'meadow-1', url: '/storefront/prod-3.png' }, { id: 'img-007b', name: 'meadow-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 14*day).toISOString() },
  { id: 'prd-008', name: 'Pashmina Fingerless Gloves', slug: 'pashmina-fingerless-gloves', sku: 'ZAE-AC-001', category: 'cat-005', basePrice: 3200, discountPrice: 2800, costPrice: 1200, quantity: 2, lowStockThreshold: 5, status: 'published', tags: ['accessories', 'gift'], material: '100% Pashmina', color: 'Charcoal', size: 'One Size', description: 'Refined fingerless gloves for the modern traveller.', images: [{ id: 'img-008a', name: 'gloves-1', url: '/storefront/prod-stack.png' }, { id: 'img-008b', name: 'gloves-2', url: '/storefront/prod-1.png' }], createdAt: new Date(now - 12*day).toISOString() },
  { id: 'prd-009', name: 'Stone Mountain Shawl', slug: 'stone-mountain-shawl', sku: 'ZAE-SH-004', category: 'cat-001', basePrice: 13500, discountPrice: null, costPrice: 5800, quantity: 9, lowStockThreshold: 5, status: 'published', tags: ['new-arrival'], material: '100% Pashmina', color: 'Mountain Stone', size: 'Large (200×70cm)', description: 'The weathered beauty of Himalayan rock translated into soft Pashmina.', images: [{ id: 'img-009a', name: 'stone-1', url: '/storefront/prod-stack.png' }, { id: 'img-009b', name: 'stone-2', url: '/storefront/prod-3.png' }], createdAt: new Date(now - 10*day).toISOString() },
  { id: 'prd-010', name: 'Cream Pashmina Stole', slug: 'cream-pashmina-stole', sku: 'ZAE-ST-003', category: 'cat-002', basePrice: 6500, discountPrice: 5800, costPrice: 2600, quantity: 22, lowStockThreshold: 4, status: 'published', tags: ['classic'], material: '100% Pashmina', color: 'Raw Cream', size: 'Standard (190×60cm)', description: 'The purest expression of Pashmina. Undyed, unadorned, unmatched.', images: [{ id: 'img-010a', name: 'cream-1', url: '/storefront/prod-1.png' }, { id: 'img-010b', name: 'cream-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 8*day).toISOString() },
  { id: 'prd-011', name: 'Alpine Pine Blanket', slug: 'alpine-pine-blanket', sku: 'ZAE-BL-002', category: 'cat-003', basePrice: 24500, discountPrice: null, costPrice: 10500, quantity: 4, lowStockThreshold: 3, status: 'published', tags: ['luxury'], material: '100% Pashmina', color: 'Forest Green', size: 'King (240×120cm)', description: 'For those who seek warmth in the grandest sense.', images: [{ id: 'img-011a', name: 'alpine-1', url: '/storefront/prod-stack.png' }, { id: 'img-011b', name: 'alpine-2', url: '/storefront/prod-3.png' }], createdAt: new Date(now - 7*day).toISOString() },
  { id: 'prd-012', name: 'Blush Rose Scarf', slug: 'blush-rose-scarf', sku: 'ZAE-SC-002', category: 'cat-004', basePrice: 4800, discountPrice: null, costPrice: 1900, quantity: 17, lowStockThreshold: 6, status: 'published', tags: ['gift'], material: '70% Pashmina, 30% Silk', color: 'Dusty Rose', size: 'Standard (170×50cm)', description: 'Delicate dusty rose tones that soften any ensemble.', images: [{ id: 'img-012a', name: 'blush-1', url: '/storefront/cat-stoles.png' }, { id: 'img-012b', name: 'blush-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 6*day).toISOString() },
  { id: 'prd-013', name: 'Night Ember Shawl', slug: 'night-ember-shawl', sku: 'ZAE-SH-005', category: 'cat-001', basePrice: 15800, discountPrice: 13500, costPrice: 6800, quantity: 6, lowStockThreshold: 5, status: 'published', tags: ['luxury', 'bestseller'], material: '100% Pashmina', color: 'Midnight Brown', size: 'Large (200×70cm)', description: 'Dark, rich, and deeply woven — for evenings that deserve something extraordinary.', images: [{ id: 'img-013a', name: 'ember-1', url: '/storefront/prod-3.png' }, { id: 'img-013b', name: 'ember-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 5*day).toISOString() },
  { id: 'prd-014', name: 'Cloud White Stole', slug: 'cloud-white-stole', sku: 'ZAE-ST-004', category: 'cat-002', basePrice: 7000, discountPrice: null, costPrice: 2900, quantity: 13, lowStockThreshold: 4, status: 'published', tags: ['wedding', 'gift'], material: '100% Pashmina', color: 'Snow White', size: 'Standard (190×60cm)', description: 'Pristine white Pashmina, the choice for celebrations and milestones.', images: [{ id: 'img-014a', name: 'cloud-1', url: '/storefront/prod-1.png' }, { id: 'img-014b', name: 'cloud-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 4*day).toISOString() },
  { id: 'prd-015', name: 'Kani Weave Shawl', slug: 'kani-weave-shawl', sku: 'ZAE-SH-006', category: 'cat-001', basePrice: 28000, discountPrice: null, costPrice: 13000, quantity: 3, lowStockThreshold: 2, status: 'published', tags: ['heritage', 'luxury', 'limited'], material: '100% Pashmina', color: 'Multi', size: 'Large (200×70cm)', description: 'Kani loom weaving — the ancient art of Kanihama village preserved in every thread.', images: [{ id: 'img-015a', name: 'kani-1', url: '/storefront/prod-2.png' }, { id: 'img-015b', name: 'kani-2', url: '/storefront/cat-embroidered.png' }], createdAt: new Date(now - 3*day).toISOString() },
  { id: 'prd-016', name: 'Desert Dusk Scarf', slug: 'desert-dusk-scarf', sku: 'ZAE-SC-003', category: 'cat-004', basePrice: 5200, discountPrice: 4500, costPrice: 2100, quantity: 20, lowStockThreshold: 6, status: 'published', tags: ['seasonal'], material: '70% Pashmina, 30% Silk', color: 'Terracotta', size: 'Standard (170×50cm)', description: 'Warm terracotta tones that echo the ochre earth of Kashmir in late summer.', images: [{ id: 'img-016a', name: 'desert-1', url: '/storefront/prod-3.png' }, { id: 'img-016b', name: 'desert-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now - 2*day).toISOString() },
  { id: 'prd-017', name: 'Midnight Throw Blanket', slug: 'midnight-throw-blanket', sku: 'ZAE-BL-003', category: 'cat-003', basePrice: 21000, discountPrice: null, costPrice: 9200, quantity: 7, lowStockThreshold: 3, status: 'draft', tags: ['upcoming'], material: '100% Pashmina', color: 'Deep Indigo', size: 'Queen (200×100cm)', description: 'Deep indigo inspired by the ink-dark nights over the Himalayas.', images: [{ id: 'img-017a', name: 'indigo-1', url: '/storefront/prod-stack.png' }, { id: 'img-017b', name: 'indigo-2', url: '/storefront/prod-3.png' }], createdAt: new Date(now - 1*day).toISOString() },
  { id: 'prd-018', name: 'Pashmina Infinity Wrap', slug: 'pashmina-infinity-wrap', sku: 'ZAE-ST-005', category: 'cat-002', basePrice: 8500, discountPrice: null, costPrice: 3500, quantity: 11, lowStockThreshold: 4, status: 'published', tags: ['modern'], material: '100% Pashmina', color: 'Warm Taupe', size: 'One Size', description: 'A modern infinity silhouette meets centuries of Pashmina craft.', images: [{ id: 'img-018a', name: 'infinity-1', url: '/storefront/prod-stack.png' }, { id: 'img-018b', name: 'infinity-2', url: '/storefront/prod-1.png' }], createdAt: new Date(now - 1*day).toISOString() },
  { id: 'prd-019', name: 'Sozni Embroidered Shawl', slug: 'sozni-embroidered-shawl', sku: 'ZAE-SH-007', category: 'cat-001', basePrice: 32000, discountPrice: null, costPrice: 15000, quantity: 2, lowStockThreshold: 2, status: 'published', tags: ['heritage', 'luxury', 'limited'], material: '100% Pashmina', color: 'Ivory', size: 'Large (200×70cm)', description: 'Hand-embroidered Sozni work — the needle art of Kashmir at its most refined.', images: [{ id: 'img-019a', name: 'sozni-1', url: '/storefront/cat-embroidered.png' }, { id: 'img-019b', name: 'sozni-2', url: '/storefront/prod-2.png' }], createdAt: new Date(now).toISOString() },
  { id: 'prd-020', name: 'Pashmina Baby Blanket', slug: 'pashmina-baby-blanket', sku: 'ZAE-BL-004', category: 'cat-003', basePrice: 9800, discountPrice: 8500, costPrice: 4200, quantity: 14, lowStockThreshold: 5, status: 'published', tags: ['gift', 'baby'], material: '100% Baby Pashmina', color: 'Soft Pink', size: 'Baby (120×80cm)', description: 'Softer than a whisper — pure baby Pashmina for the most precious gift.', images: [{ id: 'img-020a', name: 'baby-1', url: '/storefront/cat-stoles.png' }, { id: 'img-020b', name: 'baby-2', url: '/storefront/prod-stack.png' }], createdAt: new Date(now).toISOString() },
];

export const MOCK_CUSTOMERS = [
  { id: 'cus-001', name: 'Priya Sharma',      email: 'priya@example.com',   phone: '+91 98001 11234',    city: 'Mumbai',       country: 'India',       totalSpent: 38600, orderCount: 3, avgOrderValue: 12867, status: 'active',   joinedAt: new Date(now - 90*day).toISOString(),  lastOrder: new Date(now - 5*day).toISOString(),  notes: 'Prefers natural undyed pieces. Ships to Dubai frequently.' },
  { id: 'cus-002', name: 'Layla Al-Rashid',   email: 'layla@example.com',    phone: '+971 50 234 5678',  city: 'Dubai',        country: 'UAE',         totalSpent: 71200, orderCount: 5, avgOrderValue: 14240, status: 'active',   joinedAt: new Date(now - 120*day).toISOString(), lastOrder: new Date(now - 2*day).toISOString(),  notes: 'High-value client. Interested in Kani and Sozni pieces.' },
  { id: 'cus-003', name: 'James Whitfield',   email: 'james@example.com',    phone: '+44 7911 234567',   city: 'London',       country: 'UK',          totalSpent: 22500, orderCount: 2, avgOrderValue: 11250, status: 'active',   joinedAt: new Date(now - 60*day).toISOString(),  lastOrder: new Date(now - 20*day).toISOString(), notes: '' },
  { id: 'cus-004', name: 'Aiko Tanaka',        email: 'aiko@example.com',     phone: '+81 90 1234 5678',  city: 'Tokyo',        country: 'Japan',       totalSpent: 14200, orderCount: 1, avgOrderValue: 14200, status: 'active',   joinedAt: new Date(now - 45*day).toISOString(),  lastOrder: new Date(now - 45*day).toISOString(), notes: 'Discovered us through the heritage weaving blog post.' },
  { id: 'cus-005', name: 'Fatima Malik',       email: 'fatima@example.com',   phone: '+92 333 1234567',   city: 'Lahore',       country: 'Pakistan',    totalSpent: 53400, orderCount: 4, avgOrderValue: 13350, status: 'active',   joinedAt: new Date(now - 180*day).toISOString(), lastOrder: new Date(now - 8*day).toISOString(),  notes: 'Regular buyer. Interested in wedding gifting.' },
  { id: 'cus-006', name: 'Elena Petrov',       email: 'elena@example.com',    phone: '+7 916 123 4567',   city: 'Moscow',       country: 'Russia',      totalSpent: 9800,  orderCount: 1, avgOrderValue: 9800,  status: 'active',   joinedAt: new Date(now - 30*day).toISOString(),  lastOrder: new Date(now - 30*day).toISOString(), notes: '' },
  { id: 'cus-007', name: 'Omar Hassan',        email: 'omar@example.com',     phone: '+20 100 123 4567',  city: 'Cairo',        country: 'Egypt',       totalSpent: 28000, orderCount: 2, avgOrderValue: 14000, status: 'active',   joinedAt: new Date(now - 75*day).toISOString(),  lastOrder: new Date(now - 15*day).toISOString(), notes: '' },
  { id: 'cus-008', name: 'Mei Chen',           email: 'mei@example.com',      phone: '+86 138 0013 8000', city: 'Shanghai',     country: 'China',       totalSpent: 0,     orderCount: 0, avgOrderValue: 0,     status: 'inactive', joinedAt: new Date(now - 20*day).toISOString(),  lastOrder: null,                                 notes: 'Signed up, never ordered.' },
  { id: 'cus-009', name: 'Sven Larsson',       email: 'sven@example.com',     phone: '+46 70 123 4567',   city: 'Stockholm',    country: 'Sweden',      totalSpent: 17500, orderCount: 1, avgOrderValue: 17500, status: 'active',   joinedAt: new Date(now - 50*day).toISOString(),  lastOrder: new Date(now - 50*day).toISOString(), notes: 'Purchased the Kani Weave Shawl as a wedding gift.' },
  { id: 'cus-010', name: 'Amara Diallo',       email: 'amara@example.com',    phone: '+33 6 12 34 56 78', city: 'Paris',        country: 'France',      totalSpent: 45800, orderCount: 3, avgOrderValue: 15267, status: 'active',   joinedAt: new Date(now - 100*day).toISOString(), lastOrder: new Date(now - 1*day).toISOString(),  notes: 'Fashion consultant. Ships to multiple addresses.' },
  { id: 'cus-011', name: 'Arjun Mehta',        email: 'arjun@example.com',    phone: '+91 99002 22345',   city: 'Delhi',        country: 'India',       totalSpent: 19800, orderCount: 2, avgOrderValue: 9900,  status: 'active',   joinedAt: new Date(now - 55*day).toISOString(),  lastOrder: new Date(now - 12*day).toISOString(), notes: 'Interested in bulk corporate gifting.' },
  { id: 'cus-012', name: 'Sofia Rossi',        email: 'sofia@example.com',    phone: '+39 06 1234 5678',  city: 'Milan',        country: 'Italy',       totalSpent: 34200, orderCount: 2, avgOrderValue: 17100, status: 'active',   joinedAt: new Date(now - 40*day).toISOString(),  lastOrder: new Date(now - 10*day).toISOString(), notes: 'Stylist. Looking for exclusive pieces.' },
  { id: 'cus-013', name: 'Khalid Al-Mansoori', email: 'khalid@example.com',   phone: '+971 55 987 6543',  city: 'Abu Dhabi',    country: 'UAE',         totalSpent: 62000, orderCount: 4, avgOrderValue: 15500, status: 'active',   joinedAt: new Date(now - 130*day).toISOString(), lastOrder: new Date(now - 3*day).toISOString(),  notes: '' },
  { id: 'cus-014', name: 'Yuna Park',          email: 'yuna@example.com',     phone: '+82 10 1234 5678',  city: 'Seoul',        country: 'South Korea', totalSpent: 11200, orderCount: 1, avgOrderValue: 11200, status: 'active',   joinedAt: new Date(now - 25*day).toISOString(),  lastOrder: new Date(now - 25*day).toISOString(), notes: '' },
  { id: 'cus-015', name: 'Nia Williams',       email: 'nia@example.com',      phone: '+1 646 123 4567',   city: 'New York',     country: 'USA',         totalSpent: 0,     orderCount: 0, avgOrderValue: 0,     status: 'inactive', joinedAt: new Date(now - 10*day).toISOString(),  lastOrder: null,                                 notes: 'Newsletter subscriber, has not converted yet.' },
  { id: 'cus-016', name: 'Rania Jabbour',      email: 'rania@example.com',    phone: '+961 3 123 456',    city: 'Beirut',       country: 'Lebanon',     totalSpent: 26500, orderCount: 2, avgOrderValue: 13250, status: 'active',   joinedAt: new Date(now - 80*day).toISOString(),  lastOrder: new Date(now - 22*day).toISOString(), notes: '' },
  { id: 'cus-017', name: 'Dmitri Volkov',      email: 'dmitri@example.com',   phone: '+7 812 987 6543',   city: 'St Petersburg', country: 'Russia',     totalSpent: 8900,  orderCount: 1, avgOrderValue: 8900,  status: 'active',   joinedAt: new Date(now - 35*day).toISOString(),  lastOrder: new Date(now - 35*day).toISOString(), notes: '' },
  { id: 'cus-018', name: 'Hana Al-Sayed',      email: 'hana@example.com',     phone: '+966 55 123 4567',  city: 'Riyadh',       country: 'Saudi Arabia',totalSpent: 48000, orderCount: 3, avgOrderValue: 16000, status: 'active',   joinedAt: new Date(now - 110*day).toISOString(), lastOrder: new Date(now - 7*day).toISOString(),  notes: 'Gifts for extended family regularly.' },
  { id: 'cus-019', name: 'Lucas Müller',       email: 'lucas@example.com',    phone: '+49 30 1234 5678',  city: 'Berlin',       country: 'Germany',     totalSpent: 15600, orderCount: 1, avgOrderValue: 15600, status: 'active',   joinedAt: new Date(now - 48*day).toISOString(),  lastOrder: new Date(now - 48*day).toISOString(), notes: '' },
  { id: 'cus-020', name: 'Isabelle Fontaine',  email: 'isabelle@example.com', phone: '+32 2 123 4567',    city: 'Brussels',     country: 'Belgium',     totalSpent: 0,     orderCount: 0, avgOrderValue: 0,     status: 'inactive', joinedAt: new Date(now - 5*day).toISOString(),   lastOrder: null,                                 notes: '' },
];

export const MOCK_ORDERS = [
  { id: 'ord-001', orderNumber: 'ZAE-2024-0020', customer: 'cus-002', customerName: 'Layla Al-Rashid',    status: 'delivered',   items: [{ product: 'prd-015', name: 'Kani Weave Shawl', qty: 1, price: 28000 }, { product: 'prd-019', name: 'Sozni Embroidered Shawl', qty: 1, price: 32000 }], subtotal: 60000, shipping: 1200, discount: 5000, total: 56200, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: 'DHL9234567890', shippingAddress: { line1: 'Villa 12, Palm Jumeirah',      city: 'Dubai',        country: 'UAE',          zip: '00000'   }, notes: 'Gift wrap requested',                    createdAt: new Date(now - 12*day).toISOString(), updatedAt: new Date(now - 5*day).toISOString()  },
  { id: 'ord-002', orderNumber: 'ZAE-2024-0019', customer: 'cus-005', customerName: 'Fatima Malik',       status: 'shipped',     items: [{ product: 'prd-001', name: 'Himalayan Snow Shawl', qty: 2, price: 10800 }],                                                                                     subtotal: 21600, shipping: 800,  discount: 0,    total: 22400, paymentMethod: 'Bank Transfer', paymentStatus: 'paid',    trackingNumber: 'TCS8876543210', shippingAddress: { line1: '14 Model Town',                city: 'Lahore',       country: 'Pakistan',     zip: '54000'   }, notes: '',                                        createdAt: new Date(now - 6*day).toISOString(),  updatedAt: new Date(now - 2*day).toISOString()  },
  { id: 'ord-003', orderNumber: 'ZAE-2024-0018', customer: 'cus-010', customerName: 'Amara Diallo',       status: 'processing',  items: [{ product: 'prd-013', name: 'Night Ember Shawl', qty: 1, price: 13500 }, { product: 'prd-016', name: 'Desert Dusk Scarf', qty: 2, price: 4500 }],        subtotal: 22500, shipping: 1500, discount: 0,    total: 24000, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: null,            shippingAddress: { line1: '8 Rue du Faubourg',            city: 'Paris',        country: 'France',       zip: '75008'   }, notes: 'Express shipping preferred',             createdAt: new Date(now - 1*day).toISOString(),  updatedAt: new Date(now - 1*day).toISOString()  },
  { id: 'ord-004', orderNumber: 'ZAE-2024-0017', customer: 'cus-001', customerName: 'Priya Sharma',       status: 'pending',     items: [{ product: 'prd-010', name: 'Cream Pashmina Stole', qty: 1, price: 5800 }],                                                                                  subtotal: 5800,  shipping: 500,  discount: 0,    total: 6300,  paymentMethod: 'UPI',           paymentStatus: 'pending', trackingNumber: null,            shippingAddress: { line1: 'Flat 402, Andheri West',       city: 'Mumbai',       country: 'India',        zip: '400058' }, notes: '',                                        createdAt: new Date(now - 3600000).toISOString(), updatedAt: new Date(now - 3600000).toISOString() },
  { id: 'ord-005', orderNumber: 'ZAE-2024-0016', customer: 'cus-009', customerName: 'Sven Larsson',       status: 'delivered',   items: [{ product: 'prd-015', name: 'Kani Weave Shawl', qty: 1, price: 28000 }],                                                                                     subtotal: 28000, shipping: 2000, discount: 0,    total: 30000, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: 'FDX1234509876', shippingAddress: { line1: 'Stureplan 4',                  city: 'Stockholm',    country: 'Sweden',       zip: '11435'   }, notes: 'Wedding anniversary gift',               createdAt: new Date(now - 50*day).toISOString(), updatedAt: new Date(now - 45*day).toISOString() },
  { id: 'ord-006', orderNumber: 'ZAE-2024-0015', customer: 'cus-004', customerName: 'Aiko Tanaka',        status: 'delivered',   items: [{ product: 'prd-019', name: 'Sozni Embroidered Shawl', qty: 1, price: 32000 }],                                                                              subtotal: 32000, shipping: 2500, discount: 2000, total: 32500, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: 'EMS9988776655', shippingAddress: { line1: '3-1-5 Shibuya',                city: 'Tokyo',        country: 'Japan',        zip: '150-0002'}, notes: '',                                        createdAt: new Date(now - 45*day).toISOString(), updatedAt: new Date(now - 40*day).toISOString() },
  { id: 'ord-007', orderNumber: 'ZAE-2024-0014', customer: 'cus-003', customerName: 'James Whitfield',    status: 'cancelled',   items: [{ product: 'prd-005', name: 'Cedar Forest Blanket', qty: 1, price: 19500 }],                                                                                  subtotal: 19500, shipping: 1800, discount: 0,    total: 21300, paymentMethod: 'PayPal',         paymentStatus: 'refunded',trackingNumber: null,            shippingAddress: { line1: '22 Baker Street',              city: 'London',       country: 'UK',           zip: 'NW1 6XE' }, notes: 'Customer cancelled due to address change', createdAt: new Date(now - 22*day).toISOString(), updatedAt: new Date(now - 20*day).toISOString() },
  { id: 'ord-008', orderNumber: 'ZAE-2024-0013', customer: 'cus-007', customerName: 'Omar Hassan',        status: 'delivered',   items: [{ product: 'prd-003', name: 'Walnut Wood Shawl', qty: 1, price: 12500 }, { product: 'prd-006', name: 'Morning Mist Scarf', qty: 1, price: 4500 }],      subtotal: 17000, shipping: 1200, discount: 0,    total: 18200, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: 'EGY5544332211', shippingAddress: { line1: '15 Tahrir Street',              city: 'Cairo',        country: 'Egypt',        zip: '11511'   }, notes: '',                                        createdAt: new Date(now - 15*day).toISOString(), updatedAt: new Date(now - 10*day).toISOString() },
  { id: 'ord-009', orderNumber: 'ZAE-2024-0012', customer: 'cus-006', customerName: 'Elena Petrov',       status: 'delivered',   items: [{ product: 'prd-007', name: 'Autumn Meadow Shawl', qty: 1, price: 11800 }],                                                                                 subtotal: 11800, shipping: 2200, discount: 0,    total: 14000, paymentMethod: 'Wire Transfer', paymentStatus: 'paid',    trackingNumber: 'RU7766554433', shippingAddress: { line1: 'Tverskaya 15, Apt 7',          city: 'Moscow',       country: 'Russia',       zip: '125009'  }, notes: '',                                        createdAt: new Date(now - 30*day).toISOString(), updatedAt: new Date(now - 25*day).toISOString() },
  { id: 'ord-010', orderNumber: 'ZAE-2024-0011', customer: 'cus-005', customerName: 'Fatima Malik',       status: 'delivered',   items: [{ product: 'prd-014', name: 'Cloud White Stole', qty: 3, price: 7000 }, { product: 'prd-020', name: 'Pashmina Baby Blanket', qty: 1, price: 8500 }],   subtotal: 29500, shipping: 1000, discount: 1500, total: 29000, paymentMethod: 'Bank Transfer', paymentStatus: 'paid',    trackingNumber: 'TCS7654321098', shippingAddress: { line1: '14 Model Town',                city: 'Lahore',       country: 'Pakistan',     zip: '54000'   }, notes: 'Wedding gift for 3 people',              createdAt: new Date(now - 40*day).toISOString(), updatedAt: new Date(now - 35*day).toISOString() },
  { id: 'ord-011', orderNumber: 'ZAE-2024-0010', customer: 'cus-013', customerName: 'Khalid Al-Mansoori', status: 'delivered',   items: [{ product: 'prd-015', name: 'Kani Weave Shawl', qty: 2, price: 28000 }],                                                                                     subtotal: 56000, shipping: 1500, discount: 3000, total: 54500, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: 'DHL1122334455', shippingAddress: { line1: 'Al Nahyan Camp',                city: 'Abu Dhabi',    country: 'UAE',          zip: '00000'   }, notes: '',                                        createdAt: new Date(now - 55*day).toISOString(), updatedAt: new Date(now - 50*day).toISOString() },
  { id: 'ord-012', orderNumber: 'ZAE-2024-0009', customer: 'cus-012', customerName: 'Sofia Rossi',        status: 'shipped',     items: [{ product: 'prd-019', name: 'Sozni Embroidered Shawl', qty: 1, price: 32000 }, { product: 'prd-002', name: 'Saffron Garden Stole', qty: 1, price: 6800 }], subtotal: 38800, shipping: 2000, discount: 0,    total: 40800, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: 'ITA9988112233', shippingAddress: { line1: 'Via Montenapoleone 3',          city: 'Milan',        country: 'Italy',        zip: '20121'   }, notes: 'Stylist order — personal collection',    createdAt: new Date(now - 4*day).toISOString(),  updatedAt: new Date(now - 1*day).toISOString()  },
  { id: 'ord-013', orderNumber: 'ZAE-2024-0008', customer: 'cus-018', customerName: 'Hana Al-Sayed',      status: 'processing',  items: [{ product: 'prd-005', name: 'Cedar Forest Blanket', qty: 2, price: 19500 }, { product: 'prd-014', name: 'Cloud White Stole', qty: 3, price: 7000 }],    subtotal: 60000, shipping: 1800, discount: 4000, total: 57800, paymentMethod: 'Bank Transfer', paymentStatus: 'paid',    trackingNumber: null,            shippingAddress: { line1: 'Olaya District, Villa 8',      city: 'Riyadh',       country: 'Saudi Arabia', zip: '12211'   }, notes: 'Family gifting order',                   createdAt: new Date(now - 2*day).toISOString(),  updatedAt: new Date(now - 2*day).toISOString()  },
  { id: 'ord-014', orderNumber: 'ZAE-2024-0007', customer: 'cus-011', customerName: 'Arjun Mehta',        status: 'packed',      items: [{ product: 'prd-010', name: 'Cream Pashmina Stole', qty: 5, price: 5800 }],                                                                                  subtotal: 29000, shipping: 600,  discount: 2000, total: 27600, paymentMethod: 'UPI',           paymentStatus: 'paid',    trackingNumber: null,            shippingAddress: { line1: 'Connaught Place, Block A',     city: 'Delhi',        country: 'India',        zip: '110001'  }, notes: 'Corporate gifting — invoice needed',    createdAt: new Date(now - 8*day).toISOString(),  updatedAt: new Date(now - 6*day).toISOString()  },
  { id: 'ord-015', orderNumber: 'ZAE-2024-0006', customer: 'cus-014', customerName: 'Yuna Park',          status: 'delivered',   items: [{ product: 'prd-009', name: 'Stone Mountain Shawl', qty: 1, price: 13500 }],                                                                                 subtotal: 13500, shipping: 2200, discount: 0,    total: 15700, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: 'KOR3344556677', shippingAddress: { line1: 'Gangnam-gu, Apgujeong-dong',   city: 'Seoul',        country: 'South Korea', zip: '06015'   }, notes: '',                                        createdAt: new Date(now - 25*day).toISOString(), updatedAt: new Date(now - 20*day).toISOString() },
  { id: 'ord-016', orderNumber: 'ZAE-2024-0005', customer: 'cus-016', customerName: 'Rania Jabbour',      status: 'delivered',   items: [{ product: 'prd-003', name: 'Walnut Wood Shawl', qty: 1, price: 12500 }, { product: 'prd-012', name: 'Blush Rose Scarf', qty: 2, price: 4800 }],       subtotal: 22100, shipping: 1500, discount: 1000, total: 22600, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: 'LBN6677889900', shippingAddress: { line1: 'Hamra Street, Apt 12',          city: 'Beirut',       country: 'Lebanon',      zip: '1103'    }, notes: '',                                        createdAt: new Date(now - 22*day).toISOString(), updatedAt: new Date(now - 18*day).toISOString() },
  { id: 'ord-017', orderNumber: 'ZAE-2024-0004', customer: 'cus-019', customerName: 'Lucas Müller',       status: 'delivered',   items: [{ product: 'prd-013', name: 'Night Ember Shawl', qty: 1, price: 13500 }],                                                                                 subtotal: 13500, shipping: 1800, discount: 0,    total: 15300, paymentMethod: 'PayPal',         paymentStatus: 'paid',    trackingNumber: 'DEU2233445566', shippingAddress: { line1: 'Unter den Linden 21',           city: 'Berlin',       country: 'Germany',      zip: '10117'   }, notes: '',                                        createdAt: new Date(now - 48*day).toISOString(), updatedAt: new Date(now - 44*day).toISOString() },
  { id: 'ord-018', orderNumber: 'ZAE-2024-0003', customer: 'cus-002', customerName: 'Layla Al-Rashid',    status: 'delivered',   items: [{ product: 'prd-007', name: 'Autumn Meadow Shawl', qty: 1, price: 11800 }, { product: 'prd-018', name: 'Pashmina Infinity Wrap', qty: 1, price: 8500 }], subtotal: 20300, shipping: 1200, discount: 1000, total: 20500, paymentMethod: 'Credit Card',   paymentStatus: 'paid',    trackingNumber: 'DHL0011223344', shippingAddress: { line1: 'Jumeirah Lake Towers, Tower A', city: 'Dubai',        country: 'UAE',          zip: '00000'   }, notes: '',                                        createdAt: new Date(now - 65*day).toISOString(), updatedAt: new Date(now - 62*day).toISOString() },
  { id: 'ord-019', orderNumber: 'ZAE-2024-0002', customer: 'cus-017', customerName: 'Dmitri Volkov',      status: 'delivered',   items: [{ product: 'prd-001', name: 'Himalayan Snow Shawl', qty: 1, price: 10800 }],                                                                                subtotal: 10800, shipping: 2500, discount: 0,    total: 13300, paymentMethod: 'Wire Transfer', paymentStatus: 'paid',    trackingNumber: 'RU5566778899', shippingAddress: { line1: 'Nevsky Prospekt 28',             city: 'St Petersburg', country: 'Russia',      zip: '191011'  }, notes: '',                                        createdAt: new Date(now - 35*day).toISOString(), updatedAt: new Date(now - 32*day).toISOString() },
  { id: 'ord-020', orderNumber: 'ZAE-2024-0001', customer: 'cus-013', customerName: 'Khalid Al-Mansoori', status: 'refunded',    items: [{ product: 'prd-011', name: 'Alpine Pine Blanket', qty: 1, price: 24500 }],                                                                                subtotal: 24500, shipping: 1500, discount: 0,    total: 26000, paymentMethod: 'Credit Card',   paymentStatus: 'refunded',trackingNumber: 'DHL9999888877', shippingAddress: { line1: 'Khalidiyah Palace',             city: 'Abu Dhabi',    country: 'UAE',          zip: '00000'   }, notes: 'Item damaged in transit — refunded',     createdAt: new Date(now - 90*day).toISOString(), updatedAt: new Date(now - 85*day).toISOString() },
];

export const MOCK_BLOGS = [
  { id: 'blg-001', title: 'The Art of Kani Weaving: A Disappearing Heritage', slug: 'art-of-kani-weaving', excerpt: 'In the village of Kanihama, 40 kilometres from Srinagar, master weavers still sit at wooden looms that have not changed in centuries.', content: '<p>In the village of Kanihama, 40 kilometres from Srinagar, master weavers still sit at wooden looms that have not changed in centuries. The Kani technique uses small wooden spools called "kanis" instead of regular shuttles — each weaver coordinates dozens of them to create complex geometric patterns from a coded design sheet called a "talim".</p><p>A single Kani shawl can take between three months and three years to complete, depending on complexity. The most intricate pieces involve more than a thousand colour changes per row.</p>', status: 'published', author: 'adm-001', mainImage: null, bannerImage: null, categories: ['Heritage', 'Craft'], tags: ['kani', 'weaving', 'heritage', 'kashmir'], seo: { title: 'Kani Weaving: Ancient Art of Kashmir', description: 'Discover the ancient Kani weaving technique from Kanihama village, where master craftsmen create shawls that take years to complete.' }, createdAt: new Date(now - 20*day).toISOString(), publishedAt: new Date(now - 18*day).toISOString() },
  { id: 'blg-002', title: 'How to Authenticate Pure Pashmina: A Buyer\'s Guide', slug: 'authenticate-pure-pashmina', excerpt: 'The global Pashmina market is flooded with imitations. Here is how to tell the real from the rest.', content: '<p>The global Pashmina market is flooded with imitations — acrylic blends sold as pure Pashmina, machine-woven fabrics passed off as handcrafted. Knowing how to authenticate genuine Pashmina protects both the buyer and the craftspeople whose livelihoods depend on fair valuation.</p>', status: 'published', author: 'adm-002', mainImage: null, bannerImage: null, categories: ['Guide', 'Education'], tags: ['authentication', 'buying-guide', 'pashmina'], seo: { title: 'How to Authenticate Pure Pashmina', description: 'A comprehensive guide to identifying genuine Pashmina from imitations.' }, createdAt: new Date(now - 15*day).toISOString(), publishedAt: new Date(now - 14*day).toISOString() },
  { id: 'blg-003', title: 'Sozni Embroidery: The Needle Art of Kashmir', slug: 'sozni-embroidery-kashmir', excerpt: 'Sozni embroidery is to Kashmir what tapestry is to France — a textile art form refined over centuries into something extraordinary.', content: '<p>Sozni embroidery is to Kashmir what tapestry is to France. Executed with an extremely fine needle on woven Pashmina, Sozni creates floral and paisley motifs of breathtaking delicacy. A skilled craftsperson might spend a year completing a single shawl.</p>', status: 'published', author: 'adm-001', mainImage: null, bannerImage: null, categories: ['Heritage', 'Craft'], tags: ['sozni', 'embroidery', 'kashmir', 'craft'], seo: { title: 'Sozni Embroidery of Kashmir', description: 'The ancient needle art of Kashmiri Sozni embroidery, preserved in every thread.' }, createdAt: new Date(now - 10*day).toISOString(), publishedAt: new Date(now - 9*day).toISOString() },
  { id: 'blg-004', title: 'Caring for Your Pashmina: A Complete Guide', slug: 'caring-for-pashmina', excerpt: 'Pashmina, treated with respect, will last generations. Here is how to store, wash, and preserve your pieces.', content: '<p>Pashmina is extraordinarily durable when cared for correctly. The fibres, sourced from the Changthangi goat at altitudes above 14,000 feet, are designed by nature for extreme conditions. Your role is simply to avoid the conditions they were not designed for.</p>', status: 'published', author: 'adm-003', mainImage: null, bannerImage: null, categories: ['Care', 'Guide'], tags: ['care', 'maintenance', 'pashmina', 'tips'], seo: { title: 'How to Care for Your Pashmina', description: 'Complete guide on washing, storing, and preserving your Pashmina pieces for generations.' }, createdAt: new Date(now - 5*day).toISOString(), publishedAt: new Date(now - 4*day).toISOString() },
  { id: 'blg-005', title: 'The Kashmir Valley: Where Pashmina Begins', slug: 'kashmir-valley-pashmina-origins', excerpt: 'Before it becomes a shawl, Pashmina is a journey — from the high plateaus of Ladakh to the workshops of Srinagar.', content: '<p>The story of Pashmina begins not in the workshops of Srinagar but on the high plateaus of Ladakh, where the Changthangi goat grazes at elevations that would exhaust most mammals. It is this extreme altitude that causes the animal to develop its extraordinarily fine undercoat.</p>', status: 'draft', author: 'adm-001', mainImage: null, bannerImage: null, categories: ['Heritage', 'Story'], tags: ['kashmir', 'origin', 'story', 'ladakh'], seo: { title: 'Origins of Kashmiri Pashmina', description: 'The journey of Pashmina from the high plateaus of Ladakh to the world\'s finest shawls.' }, createdAt: new Date(now - 1*day).toISOString(), publishedAt: null },
  { id: 'blg-006', title: 'Loro Piana vs Kashmiri Pashmina: The Ultimate Comparison', slug: 'loro-piana-vs-kashmiri-pashmina', excerpt: 'An in-depth look at Italian industrial refinement versus the heritage of handmade Kashmiri shawls.', content: '<p>While Loro Piana represents industrial perfection in cashmere processing, Kashmiri Pashmina remains a triumph of artisan craft. Hand-spinning and hand-weaving create a softer drape and a more authentic, unique texture.</p>', status: 'published', author: 'adm-002', mainImage: null, bannerImage: null, categories: ['Heritage', 'Education'], tags: ['cashmere', 'pashmina', 'loro-piana'], seo: { title: 'Loro Piana vs Kashmiri Pashmina', description: 'Comparing Italian cashmere processing with artisanal handwoven Kashmiri pashmina.' }, createdAt: new Date(now - 25*day).toISOString(), publishedAt: new Date(now - 24*day).toISOString() },
  { id: 'blg-007', title: 'The History of the Paisley Motif in Textiles', slug: 'history-of-paisley-motif', excerpt: 'Trace the roots of the iconic paisley pattern from ancient Persia to the looms of Kashmir.', content: '<p>The paisley motif, known as "buta" in Persian, has travelled centuries of design history. Woven into shawls exported across Europe, it became a symbol of extreme luxury and status.</p>', status: 'published', author: 'adm-001', mainImage: null, bannerImage: null, categories: ['Heritage', 'Design'], tags: ['paisley', 'design-history', 'motifs'], seo: { title: 'History of the Paisley Motif in Textiles', description: 'Trace the origins and design legacy of the paisley or buta motif in Kashmiri shawls.' }, createdAt: new Date(now - 18*day).toISOString(), publishedAt: new Date(now - 17*day).toISOString() },
  { id: 'blg-008', title: 'Spinning the Yarn: The Silent Craft of Kashmir Women', slug: 'spinning-yarn-kashmir-women', excerpt: 'Meet the master spinners who turn raw Chyangra fleece into gossamer-thin pashmina yarn.', content: '<p>Behind every pashmina shawl is a silent workforce of women. Working on wooden charkhas, they hand-spin the delicate fleece into yarn that is too fine to be spun by machines.</p>', status: 'published', author: 'adm-003', mainImage: null, bannerImage: null, categories: ['Craft', 'Community'], tags: ['spinning', 'artisans', 'kashmir'], seo: { title: 'Pashmina Spinning: The Hand Craft of Kashmir Women', description: 'Learn about the hand-spinning process that converts raw goat fleece into fine pashmina yarn.' }, createdAt: new Date(now - 12*day).toISOString(), publishedAt: new Date(now - 10*day).toISOString() },
  { id: 'blg-009', title: 'Why Handcrafted Luxury is the Future of Sustainable Fashion', slug: 'handcrafted-luxury-sustainable-fashion', excerpt: 'Explore the environmental impact of slow, handwoven fabrics vs mass-produced fashion items.', content: '<p>Slow fashion is not just a trend — it is a necessity. Handcrafted luxury items, constructed locally with renewable natural fibres like pashmina, have a carbon footprint near zero.</p>', status: 'published', author: 'adm-001', mainImage: null, bannerImage: null, categories: ['Sustainability', 'Fashion'], tags: ['sustainability', 'slow-fashion', 'eco-friendly'], seo: { title: 'Handcrafted Luxury & Sustainable Fashion', description: 'How slow, handcrafted textiles like pashmina support global sustainability.' }, createdAt: new Date(now - 8*day).toISOString(), publishedAt: new Date(now - 7*day).toISOString() },
  { id: 'blg-010', title: 'A Day in Srinagar: Inside an Artisan Workshop', slug: 'day-in-srinagar-artisan-workshop', excerpt: 'Step inside the sunlit rooms where master weavers and embroiderers bring legacy patterns to life.', content: '<p>Artisan workshops in Srinagar are quiet sanctuaries of creativity. We travel to the old town to witness the incredible process of hand-weaving and embroidery first hand.</p>', status: 'published', author: 'adm-002', mainImage: null, bannerImage: null, categories: ['Story', 'Community'], tags: ['srinagar', 'workshops', 'travel'], seo: { title: 'Inside Srinagar Artisan Workshops', description: 'A photo essay and diary of visiting traditional pashmina workshops in Srinagar.' }, createdAt: new Date(now - 6*day).toISOString(), publishedAt: new Date(now - 5*day).toISOString() },
  { id: 'blg-011', title: 'Understanding Pashmina Thread Count and Microns', slug: 'pashmina-thread-count-and-microns', excerpt: 'The science behind the softness: why micron count matters more than traditional thread counts.', content: '<p>Unlike cotton, pashmina quality is determined by fiber diameter measured in microns. Pure Chyangra fleece ranges between 12 to 15 microns, making it incredibly lightweight yet insulating.</p>', status: 'draft', author: 'adm-001', mainImage: null, bannerImage: null, categories: ['Guide', 'Education'], tags: ['microns', 'technical', 'quality-guide'], seo: { title: 'Pashmina Microns and Fiber Quality Guide', description: 'Everything you need to know about fiber diameter, thread counts, and authentic pashmina.' }, createdAt: new Date(now - 3*day).toISOString(), publishedAt: null },
  { id: 'blg-012', title: 'Kashmiri Craftsmanship: From Mughal Courts to Modern Wardrobes', slug: 'kashmiri-craftsmanship-mughal-to-modern', excerpt: 'How royal patrons shaped the aesthetic of pashmina, and how it translates to modern style.', content: '<p>The Mughal emperors were the greatest patrons of Kashmiri weaving, commissioning patterns that are still replicated today. Discover the transition of these court garments into modern fashion staples.</p>', status: 'published', author: 'adm-003', mainImage: null, bannerImage: null, categories: ['Heritage', 'Design'], tags: ['history', 'royal-patrons', 'design'], seo: { title: 'History of Kashmiri Weaving - Mughal to Modern', description: 'Trace the lineage of pashmina patterns from royal Mughal commissions to contemporary wardrobes.' }, createdAt: new Date(now - 2*day).toISOString(), publishedAt: new Date(now - 1*day).toISOString() },
  { id: 'blg-013', title: 'The Natural Dyes of Kashmir: Reviving Ancient Recipes', slug: 'natural-dyes-kashmir-revival', excerpt: 'A journey into organic dyeing using walnuts, saffron, pomegranate peels, and madder roots.', content: '<p>Organic coloring is seeing a massive revival. We trace how natural ingredients sourced from the valley are used to stain pure pashmina without harsh chemical agents.</p>', status: 'published', author: 'adm-001', mainImage: null, bannerImage: null, categories: ['Sustainability', 'Craft'], tags: ['natural-dyes', 'sustainability', 'organic'], seo: { title: 'Natural Organic Dyes in Kashmiri Pashmina', description: 'Discover the traditional dyes made from native plants used to colour luxury shawls.' }, createdAt: new Date(now - 1*day).toISOString(), publishedAt: new Date(now).toISOString() },
  { id: 'blg-014', title: 'Pashmina Styling Guide: 5 Editorial Looks for Autumn', slug: 'pashmina-styling-guide-autumn', excerpt: 'How to drape, knot, and style luxury shawls for a modern editorial aesthetic.', content: '<p>From classic wraps to asymmetric folds, we show you five distinct ways to style pashmina shawls for the changing weather.</p>', status: 'draft', author: 'adm-002', mainImage: null, bannerImage: null, categories: ['Guide', 'Fashion'], tags: ['styling', 'autumn-fashion', 'draping'], seo: { title: 'How to Style Luxury Pashmina Shawls', description: '5 editorial and modern looks to elevate your autumn wardrobe using fine shawls.' }, createdAt: new Date(now).toISOString(), publishedAt: null },
  { id: 'blg-015', title: 'Woven Poetry: The Inscriptions Found on Antique Shawls', slug: 'woven-poetry-antique-shawls', excerpt: 'Uncover the hidden signatures, poems, and weaver marks embroidered on historical shawls.', content: '<p>Many antique shawls contain beautiful Persian verses and weaver signatures hidden in the margins. Learn how to decode these historical messages.</p>', status: 'published', author: 'adm-001', mainImage: null, bannerImage: null, categories: ['Heritage', 'Design'], tags: ['antiques', 'history', 'poetry'], seo: { title: 'Poetry and Weaver Signatures on Antique Shawls', description: 'Decoding the Persian inscriptions and signatures on historic Kashmiri pashmina.' }, createdAt: new Date(now).toISOString(), publishedAt: new Date().toISOString() },
];

export const MOCK_COUPONS = [
  { id: 'cpn-001', code: 'WELCOME15',    type: 'percentage', value: 15,   description: 'Welcome discount for new customers',    expiry: new Date(now + 30*day).toISOString(),  usageLimit: 100, usedCount: 34,  minOrderValue: 5000,  active: true,  createdAt: new Date(now - 60*day).toISOString() },
  { id: 'cpn-002', code: 'HERITAGE2024', type: 'fixed',      value: 2000, description: 'Heritage collection flat discount',       expiry: new Date(now + 15*day).toISOString(),  usageLimit: 50,  usedCount: 48,  minOrderValue: 15000, active: true,  createdAt: new Date(now - 30*day).toISOString() },
  { id: 'cpn-003', code: 'GIFTED10',     type: 'percentage', value: 10,   description: 'Gifting season promotion',               expiry: new Date(now - 10*day).toISOString(),  usageLimit: 200, usedCount: 176, minOrderValue: 3000,  active: false, createdAt: new Date(now - 90*day).toISOString() },
  { id: 'cpn-004', code: 'NEWSEASON20',  type: 'percentage', value: 20,   description: 'New season launch offer',               expiry: new Date(now + 60*day).toISOString(),  usageLimit: 75,  usedCount: 12,  minOrderValue: 8000,  active: true,  createdAt: new Date(now - 5*day).toISOString()  },
  { id: 'cpn-005', code: 'FLAT1000',     type: 'fixed',      value: 1000, description: 'Flat ₹1000 off any order',              expiry: new Date(now + 45*day).toISOString(),  usageLimit: 500, usedCount: 213, minOrderValue: 7000,  active: true,  createdAt: new Date(now - 45*day).toISOString() },
  { id: 'cpn-006', code: 'LOYALTY25',    type: 'percentage', value: 25,   description: 'Loyalty reward for repeat customers',   expiry: new Date(now + 20*day).toISOString(),  usageLimit: 30,  usedCount: 8,   minOrderValue: 20000, active: true,  createdAt: new Date(now - 10*day).toISOString() },
  { id: 'cpn-007', code: 'EID2024',      type: 'percentage', value: 18,   description: 'Eid celebration special',               expiry: new Date(now - 30*day).toISOString(),  usageLimit: 150, usedCount: 150, minOrderValue: 5000,  active: false, createdAt: new Date(now - 60*day).toISOString() },
  { id: 'cpn-008', code: 'DIWALI500',    type: 'fixed',      value: 500,  description: 'Diwali festive discount',               expiry: new Date(now - 5*day).toISOString(),   usageLimit: 300, usedCount: 298, minOrderValue: 3000,  active: false, createdAt: new Date(now - 45*day).toISOString() },
  { id: 'cpn-009', code: 'FIRSTORDER',   type: 'percentage', value: 12,   description: 'First order welcome coupon',            expiry: new Date(now + 90*day).toISOString(),  usageLimit: 0,   usedCount: 87,  minOrderValue: 4000,  active: true,  createdAt: new Date(now - 120*day).toISOString() },
  { id: 'cpn-010', code: 'PREMIUM30',    type: 'percentage', value: 30,   description: 'Exclusive premium client discount',     expiry: new Date(now + 10*day).toISOString(),  usageLimit: 10,  usedCount: 3,   minOrderValue: 30000, active: true,  createdAt: new Date(now - 2*day).toISOString()  },
  { id: 'cpn-011', code: 'WINTER2024',   type: 'fixed',      value: 1500, description: 'Winter collection flat discount',       expiry: new Date(now + 30*day).toISOString(),  usageLimit: 100, usedCount: 41,  minOrderValue: 10000, active: true,  createdAt: new Date(now - 15*day).toISOString() },
  { id: 'cpn-012', code: 'REFERRAL10',   type: 'percentage', value: 10,   description: 'Referral programme reward',             expiry: new Date(now + 180*day).toISOString(), usageLimit: 0,   usedCount: 23,  minOrderValue: 0,     active: true,  createdAt: new Date(now - 90*day).toISOString() },
  { id: 'cpn-013', code: 'SUMMER15',     type: 'percentage', value: 15,   description: 'Summer clearance sale',                 expiry: new Date(now - 60*day).toISOString(),  usageLimit: 200, usedCount: 189, minOrderValue: 5000,  active: false, createdAt: new Date(now - 120*day).toISOString() },
  { id: 'cpn-014', code: 'BULK2500',     type: 'fixed',      value: 2500, description: 'Bulk order discount (5+ items)',        expiry: new Date(now + 60*day).toISOString(),  usageLimit: 20,  usedCount: 5,   minOrderValue: 25000, active: true,  createdAt: new Date(now - 20*day).toISOString() },
  { id: 'cpn-015', code: 'ANNIVERSARY',  type: 'percentage', value: 22,   description: 'Brand anniversary special discount',   expiry: new Date(now + 7*day).toISOString(),   usageLimit: 50,  usedCount: 31,  minOrderValue: 12000, active: true,  createdAt: new Date(now - 1*day).toISOString()  },
];

export const MOCK_NEWSLETTER = [
  { id: 'ns-001', email: 'priya@example.com', name: 'Priya Sharma', subscribedAt: new Date(now - 90*day).toISOString(), status: 'active' },
  { id: 'ns-002', email: 'layla@example.com', name: 'Layla Al-Rashid', subscribedAt: new Date(now - 80*day).toISOString(), status: 'active' },
  { id: 'ns-003', email: 'james@example.com', name: 'James Whitfield', subscribedAt: new Date(now - 70*day).toISOString(), status: 'active' },
  { id: 'ns-004', email: 'aiko@example.com', name: 'Aiko Tanaka', subscribedAt: new Date(now - 60*day).toISOString(), status: 'active' },
  { id: 'ns-005', email: 'fatima@example.com', name: 'Fatima Malik', subscribedAt: new Date(now - 55*day).toISOString(), status: 'active' },
  { id: 'ns-006', email: 'elena@example.com', name: 'Elena Petrov', subscribedAt: new Date(now - 50*day).toISOString(), status: 'active' },
  { id: 'ns-007', email: 'omar@example.com', name: 'Omar Hassan', subscribedAt: new Date(now - 45*day).toISOString(), status: 'active' },
  { id: 'ns-008', email: 'mei@example.com', name: 'Mei Chen', subscribedAt: new Date(now - 40*day).toISOString(), status: 'unsubscribed' },
  { id: 'ns-009', email: 'sven@example.com', name: 'Sven Larsson', subscribedAt: new Date(now - 35*day).toISOString(), status: 'active' },
  { id: 'ns-010', email: 'amara@example.com', name: 'Amara Diallo', subscribedAt: new Date(now - 30*day).toISOString(), status: 'active' },
  { id: 'ns-011', email: 'rafiq@example.com', name: 'Rafiq Ahmed', subscribedAt: new Date(now - 25*day).toISOString(), status: 'active' },
  { id: 'ns-012', email: 'zara@example.com', name: 'Zara Begum', subscribedAt: new Date(now - 20*day).toISOString(), status: 'active' },
  { id: 'ns-013', email: 'pierre@example.com', name: 'Pierre Laurent', subscribedAt: new Date(now - 15*day).toISOString(), status: 'active' },
  { id: 'ns-014', email: 'nina@example.com', name: 'Nina Kovač', subscribedAt: new Date(now - 10*day).toISOString(), status: 'active' },
  { id: 'ns-015', email: 'yuki@example.com', name: 'Yuki Watanabe', subscribedAt: new Date(now - 5*day).toISOString(), status: 'active' },
];

export const MOCK_REVENUE_CHART = [
  { month: 'Feb', revenue: 124000, orders: 9 },
  { month: 'Mar', revenue: 168000, orders: 13 },
  { month: 'Apr', revenue: 142000, orders: 11 },
  { month: 'May', revenue: 195000, orders: 15 },
  { month: 'Jun', revenue: 221000, orders: 17 },
  { month: 'Jul', revenue: 187000, orders: 14 },
  { month: 'Aug', revenue: 243000, orders: 19 },
  { month: 'Sep', revenue: 268000, orders: 21 },
  { month: 'Oct', revenue: 312000, orders: 24 },
  { month: 'Nov', revenue: 389000, orders: 30 },
  { month: 'Dec', revenue: 445000, orders: 35 },
  { month: 'Jan', revenue: 298000, orders: 23 },
];

export const MOCK_CATEGORY_SALES = [
  { name: 'Shawls', value: 58 },
  { name: 'Stoles', value: 22 },
  { name: 'Blankets', value: 12 },
  { name: 'Scarves', value: 6 },
  { name: 'Accessories', value: 2 },
];

export const MOCK_ACTIVITY = [
  { id: 1, type: 'order', message: 'New order ZAE-2024-0010 from Layla Al-Rashid', time: '2 minutes ago', dot: 'walnut' },
  { id: 2, type: 'product', message: 'Sozni Embroidered Shawl stock updated to 2 units', time: '18 minutes ago', dot: 'saffron' },
  { id: 3, type: 'order', message: 'Order ZAE-2024-0009 shipped to Lahore', time: '1 hour ago', dot: 'cedar' },
  { id: 4, type: 'customer', message: 'New customer registration — Amara Diallo (Paris)', time: '2 hours ago', dot: 'walnut' },
  { id: 5, type: 'blog', message: '"Caring for Your Pashmina" published by Amir Shah', time: '4 hours ago', dot: 'cedar' },
  { id: 6, type: 'coupon', message: 'Coupon GIFTED10 expired', time: '10 days ago', dot: 'saffron' },
];

export const MOCK_LOW_STOCK = MOCK_PRODUCTS.filter(p => p.quantity <= p.lowStockThreshold);

export const MOCK_SETTINGS = {
  storeName: 'Zaevyul Pashmina',
  tagline: 'Timeless · Authentic · Handcrafted',
  email: 'hello@zaevyul.com',
  phone: '+91 194 123 4567',
  address: 'Residency Road, Srinagar, Jammu & Kashmir 190001',
  currency: 'INR',
  currencySymbol: '₹',
  taxRate: 5,
  freeShippingAbove: 10000,
  socialLinks: {
    instagram: 'https://instagram.com/zaevyul',
    facebook: '',
    twitter: '',
    pinterest: '',
  },
  paymentGateways: {
    razorpay: { keyId: 'rzp_live_XXXXXXXXXX', enabled: true },
    stripe: { keyId: '', enabled: false },
  },
};

// Helper: format currency
export const formatCurrency = (amount, symbol = '₹') =>
  `${symbol}${amount.toLocaleString('en-IN')}`;

// Helper: format date
export const formatDate = (iso) => {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
};

// Helper: time ago
export const timeAgo = (iso) => {
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  return `${days}d ago`;
};

// Helper: order status config
export const ORDER_STATUS = {
  pending:    { label: 'Pending',    badge: 'badge-amber' },
  processing: { label: 'Processing', badge: 'badge-blue' },
  packed:     { label: 'Packed',     badge: 'badge-teal' },
  shipped:    { label: 'Shipped',    badge: 'badge-blue' },
  delivered:  { label: 'Delivered',  badge: 'badge-green' },
  cancelled:  { label: 'Cancelled',  badge: 'badge-red' },
  refunded:   { label: 'Refunded',   badge: 'badge-gray' },
};

export const PRODUCT_STATUS = {
  published: { label: 'Published', badge: 'badge-green' },
  draft:     { label: 'Draft',     badge: 'badge-gray' },
  archived:  { label: 'Archived',  badge: 'badge-red' },
};
